### ISSUE TITLE
Add basic documentation

### ISSUE THREAD

**Issue by gabrieag** [gabrieag/change-detec#3]
Improve `README.md` and add pointers to test scripts.

**Comment by asherbender** [comment]
Indeed. 

I was a bit disappointed to find out Github currently does not support equations in the `README.md` - so they can't be rendered on the home-page (unless they are imbedded as images). [Sphinx](http://sphinx-doc.org/) is good for developing API docs. It can even include equations - which is pretty useful for ML algorithms. The down side is that users will probably never read it! Good example code is probably more useful?

Another thought is the `README.md` could be written as a `README.rst` which is a bit more 'pythonic' and cosistent with Sphinx ReST markup. We should also include:
- A license (probably BSD or Apache)
- setup.py config for installing the package

**Comment by gabrieag** [comment]
This sounds great! The documentation you wrote for your [Bayesian linear model](https://github.com/asherbender/bayesian-linear-model) looks awesome. I don't know if I'll find the time to do such a thorough job, so for now I think I'll just stick to plain text.
